apiVersion: v1
kind: Pod
metadata:
  name: redis-db
  namespace: omni-prod
  labels:
    app: omni
    tier: database
spec:
  tolerations:
    - key: workload
      operator: Equal
      value: database
      effect: NoSchedule
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: tier
                operator: In
                values:
                  - db
  containers:
    - name: redis
      image: redis:alpine
      ports:
        - containerPort: 6379
      resources:
        requests:
          cpu: 100m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 128Mi
      livenessProbe:
        tcpSocket:
          port: 6379
        initialDelaySeconds: 5
        periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: redis-db-svc
  namespace: omni-prod
spec:
  type: ClusterIP
  selector:
    app: omni
    tier: database
  ports:
    - port: 6379
      targetPort: 6379