apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: omni-prod
  labels:
    app: omni
    tier: database
spec:
  tolerations:
  - key: workload
    operator: Equal
    value: database
    effect: NoSchedule
  affinity:
    NodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: tier
            operator: In
            values:
            - db
  containers:
  - image: redis:alpine
    port:
      containerPort: 6379
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi
    LivenessProbe:
      tcpSocket:
        port: 6379
      initialDelaySeconds: 5
      periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: redis-db-svc
  namespace: omni-prod
spec:
  type: ClusterIP
  selector:
    app: omni
    tier: database
  ports:
  - port: 6379
    targetPort: 6379